apiVersion: v1
kind: Service
metadata: 
  name: auth-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: auth-deployment
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80